hwi_oauth:
    firewall_names: [herd_management]
    resource_owners:
        twitter:
            type:          twitter
            client_id:     "%twitter_client_id%"
            client_secret: "%twitter_client_secret%"
    connect:
        confirmation:              true
        registration_form:         elewant.security.registration.form
        registration_form_handler: elewant.security.registration.form_handler
        account_connector:         elewant.security.account.connector

services:
    elewant.security.registration.form:
        class: Elewant\UserBundle\Form\UserType
        factory: "form.factory:create"
        arguments: [ 'Elewant\UserBundle\Form\UserType' ]

    elewant.security.registration.form_handler:
        class: Elewant\UserBundle\Form\RegistrationFormHandler
        arguments: [ '@Elewant\UserBundle\Security\UserProvider' ]

    elewant.security.account.connector: '@Elewant\UserBundle\Security\UserProvider'

    Elewant\UserBundle\Security\UserProvider:
        public: true
