prooph_event_store:
    stores:
        herd_store:
            event_store: prooph_event_store.event_store
            repositories:
                herd_collection:
                    repository_class: Elewant\Herding\Infrastructure\Prooph\ProophHerdCollection
                    aggregate_type: Elewant\Herding\DomainModel\Herd\Herd
                    aggregate_translator: prooph_event_store.aggregate_translator

    projection_managers:
        elewant_projection_manager:
            event_store: prooph_event_store.event_store
            connection: prooph_event_store.connection
            projections:
                herd_projection:
                    read_model: Elewant\Webapp\Infrastructure\ProophProjections\HerdReadModel
                    projection: Elewant\Webapp\Infrastructure\ProophProjections\HerdProjection

services:
    _defaults:
        public: false

    prooph_event_store.aggregate_translator:
        class: Prooph\EventSourcing\EventStoreIntegration\AggregateTranslator

    prooph_event_store.connection:
        class: PDO
        factory: ['@database_connection', getWrappedConnection]

    prooph_event_store.event_store:
        class: Prooph\EventStore\Pdo\MariaDbEventStore
        arguments:
            - '@prooph_event_store.message_factory'
            - '@prooph_event_store.connection'
            - '@prooph_event_store.persistence_strategy'

    prooph_event_store.persistence_strategy:
        class: Tooling\ProophEventStore\MariaDbSingleStreamStrategyWithUnescapedUnicode
