services:
    _defaults:
        public: false

    Prooph\EventStoreBusBridge\EventPublisher:
        arguments:
            - '@prooph_service_bus.herding_event_bus'
        tags:
            - { name: 'prooph_event_store.herd_store.plugin' }
