version: '3'

services:
    database:
        build: docker/mariadb
        volumes:
            - db:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: elewant
            MYSQL_DATABASE: elewant
            MYSQL_USER: elewant
            MYSQL_PASSWORD: elewant
    php-fpm:
        build: docker/php-fpm
        volumes:
            - ./:/opt/project:cached
        depends_on:
          - database
    webserver:
        build: docker/nginx
        ports:
            - "80:80"
        depends_on:
          - php-fpm
        volumes:
            - ./:/opt/project:cached
volumes:
  db:
