version: '3'

services:
    database_test:
        build: docker/mariadb
        environment:
            MYSQL_ROOT_PASSWORD: elewant
            MYSQL_DATABASE: elewant_test
            MYSQL_USER: elewant
            MYSQL_PASSWORD: elewant
    php-cli:
        build: docker/php-cli
        volumes:
        - ./:/opt/project:cached
        depends_on:
            - database_test
