version: '3'

services:
    database:
        build: docker/mariadb
        environment:
            MYSQL_ROOT_PASSWORD: elewant
            MYSQL_DATABASE: elewant
            MYSQL_USER: elewant
            MYSQL_PASSWORD: elewant
        volumes:
            - db:/var/lib/mysql

    php-cli:
        build: docker/php-cli
        depends_on:
            - database
        volumes:
            - ./:/opt/project:cached

    php-fpm:
        build: docker/php-fpm
        depends_on:
            - database
        volumes:
            - ./:/opt/project:cached

    herd-projection:
        build: docker/php-cli
        command: php bin/console event-store:projection:run herd_projection
        depends_on:
            - database
        entrypoint:
            - /opt/project/docker/wait_for_sql.sh
        volumes:
            - ./:/opt/project:cached

    webserver:
        build: docker/nginx
        depends_on:
            - php-fpm
        ports:
            - "80:80"
        volumes:
            - ./:/opt/project:cached

volumes:
    db:
