version: '3'

services:
    database-test:
        build: docker/mariadb
        environment:
            MYSQL_ROOT_PASSWORD: elewant
            MYSQL_DATABASE: elewant_test
            MYSQL_USER: elewant
            MYSQL_PASSWORD: elewant
        ports:
            - "4306:3306"

    php-cli:
        build: docker/php-cli
        depends_on:
            - database-test
        entrypoint:
            - /opt/project/docker/wait_for_test_database
        volumes:
            - ./:/opt/project:cached
