fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix:   /connect

hwi_oauth_connect:
    resource: "@HWIOAuthBundle/Resources/config/routing/connect.xml"
    prefix:   /connect

hwi_oauth_login:
    resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
    prefix:   /login

hwi_oauth_twitter_login:
    path: /connect/twitter

hwi_oauth_twitter_login_check:
    path: /login/check-twitter

hwi_oauth_logout:
    path: /logout

elewant_app:
    resource: "@ElewantAppBundle/Controller/"
    type:     annotation
    prefix:   /

