# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
    providers:
        entity_provider:
            id: elewant.security.user_provider

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        secured_area:
            anonymous: ~
            oauth:
                oauth_user_provider:
                    service:  elewant.security.user_provider
                resource_owners:
                    twitter:  hwi_oauth_twitter_login_check
                login_path:   hwi_oauth_twitter_login
                default_target_path: herd_tending
                failure_path: root
                use_forward:  false
            logout:
                path:   hwi_oauth_logout
                target: root

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
