---

- name: Provision globally
  hosts: all
  become: yes
  gather_facts: yes

  pre_tasks:
    - name: Ensure the PHP-FPM chdir exists
      file:
        path: "{{ php7_fpm_pool_chdir }}"
        owner: "{{ php7_fpm_pool_user }}"
        group: "{{ php7_fpm_pool_group }}"
        mode: 0755
        state: directory

  roles:
    - f500.debian
    - f500.locale
    - f500.ntp
    - f500.ufw
    - f500.ufw_rules
    - f500.bash
    - f500.bashrc
    - f500.vim

    - HanXHX.mysql
    - f500.php7
    - f500.php_composer
    - f500.nginx
    - f500.nodejs

  post_tasks:
    - name: Install apt packages
      apt:
        name: "{{ item }}"
        state: present
      with_items:
        - acl
        - git

    - name: Install npm packages
      npm:
        name: "{{ item }}"
        global: yes
        state: present
      with_items:
        - grunt-cli

- name: Provision develop environment
  hosts: develop
  become: no
  gather_facts: no

  tasks:
    - name: cd into /vagrant when logging in
      lineinfile:
        dest: /home/vagrant/.profile
        line: cd /vagrant
        insertafter: EOF

    - name: Copy parameters.yml
      template:
        src: "{{ inventory_dir }}/templates/app/parameters.yml.j2"
        dest: /vagrant/app/config/parameters.yml

    - name: Install composer packages
      command: composer install --quiet --no-ansi --no-interaction
      args:
        chdir: "{{ elewant_application_root }}"

    - name: Install npm packages
      npm:
        path: "{{ elewant_application_root }}"

    - name: Build assets
      command: grunt
      args:
        chdir: "{{ elewant_application_root }}"
