---

# COMMON

- name: Provision common
  hosts: all
  become: yes
  gather_facts: yes

  roles:
    - f500.debian
    - f500.locale
    - f500.ntp
    - f500.ufw
    - f500.ufw_rules
    - f500.bash
    - f500.bashrc
    - f500.vim

  post_tasks:
    - name: Install apt packages
      apt:
        name: "{{ item }}"
        state: present
      with_items: [ acl, git ]

# SPECIFICS

- name: Provision specifics
  hosts: all
  become: yes
  gather_facts: no

  pre_tasks:
    - name: Ensure the PHP-FPM chdir exists
      file:
        path: "{{ php7_fpm_pool_chdir }}"
        owner: "{{ php7_fpm_pool_user }}"
        group: "{{ php7_fpm_pool_group }}"
        mode: 0755
        state: directory

  roles:
    - HanXHX.mysql
    - f500.php7
    - f500.php_composer
    - f500.nginx

# DEVELOP

- name: Provision develop environment
  hosts: develop
  become: no
  gather_facts: no

  tasks:
    - name: cd into /vagrant when logging in
      lineinfile:
        path: /home/vagrant/.profile
        line: cd /vagrant
        insertafter: EOF

    - name: Copy parameters.yml
      template:
        src: "{{ inventory_dir }}/templates/app/parameters.yml.j2"
        dest: /vagrant/app/config/parameters.yml

    - name: Install composer packages
      command: composer install --quiet --no-ansi --no-interaction
      args:
        chdir: "{{ elewant_application_root }}"
