'command::form-herd':
    path: '/testapi/commands/form-herd'
    defaults: { _controller: elewant.api_command_controller:postAction, prooph_command_name: 'Elewant\Herding\Model\Commands\FormHerd' }

'command::adopt-elephpant':
    path: '/testapi/commands/adopt-elephpant'
    defaults: { _controller: elewant.api_command_controller:postAction, prooph_command_name: 'Elewant\Herding\Model\Commands\AdoptElePHPant' }

'command::abandon-elephpant':
    path: '/testapi/commands/abandon-elephpant'
    defaults: { _controller: elewant.api_command_controller:postAction, prooph_command_name: 'Elewant\Herding\Model\Commands\AbandonElePHPant' }

'command::abandon-herd':
    path: '/testapi/commands/abandon-herd'
    defaults: { _controller: elewant.api_command_controller:postAction, prooph_command_name: 'Elewant\Herding\Model\Commands\AbandonHerd' }

'command::rename-herd':
    path: '/testapi/commands/rename-herd'
    defaults: { _controller: elewant.api_command_controller:postAction, prooph_command_name: 'Elewant\Herding\Model\Commands\RenameHerd' }

'command::desire-breed':
    path: '/testapi/commands/desire-breed'
    defaults: { _controller: elewant.api_command_controller:postAction, prooph_command_name: 'Elewant\Herding\Model\Commands\DesireBreed' }

'command::eliminate-desire-for-breed':
    path: '/testapi/commands/eliminate-desire-for-breed'
    defaults: { _controller: elewant.api_command_controller:postAction, prooph_command_name: 'Elewant\Herding\Model\Commands\EliminateDesireForBreed' }
