imports:
    - { resource: "@ElewantAppBundle/Resources/config/event_store.yml" }
    - { resource: "@ElewantAppBundle/Resources/config/projection.yml" }
    - { resource: "@ElewantAppBundle/Resources/config/service_bus.yml" }

services:
    elewant.githubService:
        class: Elewant\AppBundle\Service\GithubService
        arguments: [ %github_username%, %github_repository% ]

    elewant.twig.breed_extention:
        class: Elewant\AppBundle\Twig\BreedExtension
        tags:
            - { name: twig.extension }
    elewant.twig.contributors_extension:
        class: Elewant\AppBundle\Twig\ContributorsExtension
        arguments: ["@elewant.githubService"]
        tags:
            -  { name: twig.extension }
    twig.extension.array:
        class: Twig_Extensions_Extension_Array
        tags:
            - { name: twig.extension }

    elewant.herd.herd_repository:
        class: Elewant\AppBundle\Repository\HerdRepository
        factory: [ "@doctrine.orm.entity_manager", getRepository ]
        arguments: [ Elewant\AppBundle\Entity\Herd ]

    elewant.event_subscriber.new_user:
        class: Elewant\AppBundle\EventSubscriber\NewUserSubscriber
        arguments: ["@elewant.herd.herd_repository", "@prooph_service_bus.herding_command_bus"]
        tags:
            - { name: kernel.event_subscriber }

    elewant.api_command_controller:
        class: Elewant\AppBundle\Controller\ApiCommandController
        arguments: ['@prooph_service_bus.herding_command_bus', '@prooph_service_bus.message_factory']

    elewant.form_herd_handler:
        class: Elewant\Herding\Model\Handlers\FormHerdHandler
        arguments: ['@herd_collection']

    elewant.adopt_elephpant_handler:
        class: Elewant\Herding\Model\Handlers\AdoptElePHPantHandler
        arguments: ['@herd_collection']

    elewant.abandon_elephpant_handler:
        class: Elewant\Herding\Model\Handlers\AbandonElePHPantHandler
        arguments: ['@herd_collection']

    elewant.abandon_herd_handler:
        class: Elewant\Herding\Model\Handlers\AbandonHerdHandler
        arguments: ['@herd_collection']
